# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(732, 608)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        login.setFont(font)
        login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        login.setAcceptDrops(False)
        login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 721, 591))
        self.label.setTabletTracking(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../../Downloads/WhatsApp Image 2021-11-11 at 7.23.08 PM.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(170, 300, 371, 221))
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_registrar = QtWidgets.QPushButton(self.frame)
        self.btn_registrar.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 14pt \"Calibri\"; color: #000000;\n"
"border-color: rgb(0, 0, 255);")
        self.btn_registrar.setObjectName("btn_registrar")
        self.gridLayout.addWidget(self.btn_registrar, 2, 2, 1, 1)
        self.btn_ingresar = QtWidgets.QPushButton(self.frame)
        self.btn_ingresar.setAcceptDrops(False)
        self.btn_ingresar.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 14pt \"Calibri\"; color: #000000;\n"
"border-color: rgb(0, 0, 255);")
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.gridLayout.addWidget(self.btn_ingresar, 2, 0, 1, 2)
        self.input_Password = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.input_Password.setFont(font)
        self.input_Password.setAcceptDrops(True)
        self.input_Password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_Password.setObjectName("input_Password")
        self.gridLayout.addWidget(self.input_Password, 1, 2, 1, 1)
        self.input_usuario = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.input_usuario.setFont(font)
        self.input_usuario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_usuario.setObjectName("input_usuario")
        self.gridLayout.addWidget(self.input_usuario, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)
        login.setTabOrder(self.input_usuario, self.input_Password)
        login.setTabOrder(self.input_Password, self.btn_ingresar)
        login.setTabOrder(self.btn_ingresar, self.btn_registrar)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "EZEQUIEL"))
        self.btn_registrar.setText(_translate("login", "Registrar"))
        self.btn_ingresar.setText(_translate("login", "Ingresar"))
        self.input_Password.setPlaceholderText(_translate("login", "contraseña"))
        self.input_usuario.setPlaceholderText(_translate("login", "usuario"))
        self.label_3.setText(_translate("login", "Contraseña: "))
        self.label_2.setText(_translate("login", "Nombre de usuario: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
