from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgregarProducto(object):
    def setupUi(self, AgregarProducto):
        AgregarProducto.setObjectName("AgregarProducto")
        AgregarProducto.resize(650, 550)
        self.centralwidget = QtWidgets.QWidget(AgregarProducto)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 70, 441, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.input_fecha_ingreso = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_fecha_ingreso.setFont(font)
        self.input_fecha_ingreso.setObjectName("input_fecha_ingreso")
        self.gridLayout.addWidget(self.input_fecha_ingreso, 7, 1, 1, 1)
        self.lbl_fecha_ingreso = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fecha_ingreso.setFont(font)
        self.lbl_fecha_ingreso.setObjectName("lbl_fecha_ingreso")
        self.gridLayout.addWidget(self.lbl_fecha_ingreso, 7, 0, 1, 1)
        self.lbl_nombre = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nombre.setFont(font)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.gridLayout.addWidget(self.lbl_nombre, 3, 0, 1, 1)
        self.lbl_precio = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_precio.setFont(font)
        self.lbl_precio.setObjectName("lbl_precio")
        self.gridLayout.addWidget(self.lbl_precio, 9, 0, 1, 1)
        self.input_fecha_vencimiento = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_fecha_vencimiento.setFont(font)
        self.input_fecha_vencimiento.setObjectName("input_fecha_vencimiento")
        self.gridLayout.addWidget(self.input_fecha_vencimiento, 8, 1, 1, 1)
        self.lbl_lote = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lote.setFont(font)
        self.lbl_lote.setObjectName("lbl_lote")
        self.gridLayout.addWidget(self.lbl_lote, 2, 0, 1, 1)
        self.input_detalle = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_detalle.setFont(font)
        self.input_detalle.setObjectName("input_detalle")
        self.gridLayout.addWidget(self.input_detalle, 5, 1, 1, 1)
        self.lbl_fecha_vencimiento = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fecha_vencimiento.setFont(font)
        self.lbl_fecha_vencimiento.setObjectName("lbl_fecha_vencimiento")
        self.gridLayout.addWidget(self.lbl_fecha_vencimiento, 8, 0, 1, 1)
        self.lbl_cantidad = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_cantidad.setFont(font)
        self.lbl_cantidad.setObjectName("lbl_cantidad")
        self.gridLayout.addWidget(self.lbl_cantidad, 6, 0, 1, 1)
        self.lbl_codigo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_codigo.setFont(font)
        self.lbl_codigo.setObjectName("lbl_codigo")
        self.gridLayout.addWidget(self.lbl_codigo, 1, 0, 1, 1)
        self.input_cod = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_cod.setFont(font)
        self.input_cod.setObjectName("input_cod")
        self.gridLayout.addWidget(self.input_cod, 1, 1, 1, 1)
        self.lbl_detalle = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_detalle.setFont(font)
        self.lbl_detalle.setObjectName("lbl_detalle")
        self.gridLayout.addWidget(self.lbl_detalle, 5, 0, 1, 1)
        self.input_cantidad = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_cantidad.setFont(font)
        self.input_cantidad.setObjectName("input_cantidad")
        self.gridLayout.addWidget(self.input_cantidad, 6, 1, 1, 1)
        self.input_precio = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_precio.setFont(font)
        self.input_precio.setObjectName("input_precio")
        self.gridLayout.addWidget(self.input_precio, 9, 1, 1, 1)
        self.input_lote = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_lote.setFont(font)
        self.input_lote.setObjectName("input_lote")
        self.gridLayout.addWidget(self.input_lote, 2, 1, 1, 1)
        self.input_nombre = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_nombre.setFont(font)
        self.input_nombre.setObjectName("input_nombre")
        self.gridLayout.addWidget(self.input_nombre, 3, 1, 1, 1)
        self.lbl_agregarProducto = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_agregarProducto.setFont(font)
        self.lbl_agregarProducto.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_agregarProducto.setObjectName("lbl_agregarProducto")
        self.gridLayout.addWidget(self.lbl_agregarProducto, 0, 0, 1, 5)
        self.btn_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar.setGeometry(QtCore.QRect(170, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_agregar.setFont(font)
        self.btn_agregar.setObjectName("btn_agregar")
        self.btn_borrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_borrar.setGeometry(QtCore.QRect(370, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_borrar.setFont(font)
        self.btn_borrar.setObjectName("btn_borrar")
        AgregarProducto.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AgregarProducto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        AgregarProducto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AgregarProducto)
        self.statusbar.setObjectName("statusbar")
        AgregarProducto.setStatusBar(self.statusbar)

        self.retranslateUi(AgregarProducto)
        QtCore.QMetaObject.connectSlotsByName(AgregarProducto)

    def retranslateUi(self, AgregarProducto):
        _translate = QtCore.QCoreApplication.translate
        AgregarProducto.setWindowTitle(_translate("AgregarProducto", "AgregarProducto"))
        self.input_fecha_ingreso.setPlaceholderText(_translate("AgregarProducto", "fecha_ingreso"))
        self.lbl_fecha_ingreso.setText(_translate("AgregarProducto", "Fecha Ingreso:"))
        self.lbl_nombre.setText(_translate("AgregarProducto", "Nombre: "))
        self.lbl_precio.setText(_translate("AgregarProducto", "Precio: "))
        self.input_fecha_vencimiento.setPlaceholderText(_translate("AgregarProducto", "fecha_vencimiento"))
        self.lbl_lote.setText(_translate("AgregarProducto", "Lote:"))
        self.input_detalle.setPlaceholderText(_translate("AgregarProducto", "detalle"))
        self.lbl_fecha_vencimiento.setText(_translate("AgregarProducto", "Fecha Vencimiento: "))
        self.lbl_cantidad.setText(_translate("AgregarProducto", "Cantidad: "))
        self.lbl_codigo.setText(_translate("AgregarProducto", "Código: "))
        self.input_cod.setPlaceholderText(_translate("AgregarProducto", "código"))
        self.lbl_detalle.setText(_translate("AgregarProducto", "Detalle: "))
        self.input_cantidad.setPlaceholderText(_translate("AgregarProducto", "cantidad"))
        self.input_precio.setPlaceholderText(_translate("AgregarProducto", "precio"))
        self.input_lote.setPlaceholderText(_translate("AgregarProducto", "lote"))
        self.input_nombre.setPlaceholderText(_translate("AgregarProducto", "nombre"))
        self.lbl_agregarProducto.setText(_translate("AgregarProducto", "Agregar Producto "))
        self.btn_agregar.setText(_translate("AgregarProducto", "AGREGAR"))
        self.btn_borrar.setText(_translate("AgregarProducto", "BORRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarProducto = QtWidgets.QMainWindow()
    ui = Ui_AgregarProducto()
    ui.setupUi(AgregarProducto)
    AgregarProducto.show()
    sys.exit(app.exec_())