from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AgregarProducto(object):
    def setupUi(self, AgregarProducto):
        AgregarProducto.setObjectName("AgregarProducto")
        AgregarProducto.resize(589, 593)
        self.centralwidget = QtWidgets.QWidget(AgregarProducto)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 110, 300, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.input_cantidad = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_cantidad.setFont(font)
        self.input_cantidad.setObjectName("input_cantidad")
        self.gridLayout.addWidget(self.input_cantidad, 1, 1, 1, 1)
        self.input_nombre = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_nombre.setFont(font)
        self.input_nombre.setObjectName("input_nombre")
        self.gridLayout.addWidget(self.input_nombre, 0, 1, 1, 1)
        self.input_stockMaximo = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_stockMaximo.setFont(font)
        self.input_stockMaximo.setObjectName("input_stockMaximo")
        self.gridLayout.addWidget(self.input_stockMaximo, 2, 1, 1, 1)
        self.input_precio = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_precio.setFont(font)
        self.input_precio.setObjectName("input_precio")
        self.gridLayout.addWidget(self.input_precio, 4, 1, 1, 1)
        self.input_stockMinimo = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_stockMinimo.setFont(font)
        self.input_stockMinimo.setObjectName("input_stockMinimo")
        self.gridLayout.addWidget(self.input_stockMinimo, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 49, 298, 64))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.btn_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar.setGeometry(QtCore.QRect(315, 522, 125, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_agregar.setFont(font)
        self.btn_agregar.setObjectName("btn_agregar")
        AgregarProducto.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AgregarProducto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 21))
        self.menubar.setObjectName("menubar")
        AgregarProducto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AgregarProducto)
        self.statusbar.setObjectName("statusbar")
        AgregarProducto.setStatusBar(self.statusbar)

        self.retranslateUi(AgregarProducto)
        QtCore.QMetaObject.connectSlotsByName(AgregarProducto)

    def retranslateUi(self, AgregarProducto):
        _translate = QtCore.QCoreApplication.translate
        AgregarProducto.setWindowTitle(_translate("AgregarProducto", "Ezequiel"))
        self.label.setText(_translate("AgregarProducto", "Nombre: "))
        self.input_cantidad.setPlaceholderText(_translate("AgregarProducto", "cantidad"))
        self.input_nombre.setPlaceholderText(_translate("AgregarProducto", "nombre"))
        self.input_stockMaximo.setPlaceholderText(_translate("AgregarProducto", "stockMáximo"))
        self.input_precio.setPlaceholderText(_translate("AgregarProducto", "precio"))
        self.input_stockMinimo.setPlaceholderText(_translate("AgregarProducto", "stockMínimo"))
        self.label_3.setText(_translate("AgregarProducto", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Stock Máximo: </span></p></body></html>"))
        self.label_5.setText(_translate("AgregarProducto", "Precio: "))
        self.label_2.setText(_translate("AgregarProducto", "Cantidad: "))
        self.label_4.setText(_translate("AgregarProducto", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Stock Mínimo: </span></p></body></html>"))
        self.label_6.setText(_translate("AgregarProducto", "Agregar Producto "))
        self.btn_agregar.setText(_translate("AgregarProducto", "AGREGAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarProducto = QtWidgets.QMainWindow()
    ui = Ui_AgregarProducto()
    ui.setupUi(AgregarProducto)
    AgregarProducto.show()
    sys.exit(app.exec_())
