from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 70, 441, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.input_fecha_ingreso = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_fecha_ingreso.setFont(font)
        self.input_fecha_ingreso.setObjectName("input_fecha_ingreso")
        self.gridLayout.addWidget(self.input_fecha_ingreso, 7, 1, 1, 1)
        self.lbl_fecha_ingreso = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fecha_ingreso.setFont(font)
        self.lbl_fecha_ingreso.setObjectName("lbl_fecha_ingreso")
        self.gridLayout.addWidget(self.lbl_fecha_ingreso, 7, 0, 1, 1)
        self.lbl_nombre = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nombre.setFont(font)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.gridLayout.addWidget(self.lbl_nombre, 3, 0, 1, 1)
        self.lbl_precio = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_precio.setFont(font)
        self.lbl_precio.setObjectName("lbl_precio")
        self.gridLayout.addWidget(self.lbl_precio, 9, 0, 1, 1)
        self.input_fecha_vencimiento = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_fecha_vencimiento.setFont(font)
        self.input_fecha_vencimiento.setObjectName("input_fecha_vencimiento")
        self.gridLayout.addWidget(self.input_fecha_vencimiento, 8, 1, 1, 1)
        self.lbl_lote = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_lote.setFont(font)
        self.lbl_lote.setObjectName("lbl_lote")
        self.gridLayout.addWidget(self.lbl_lote, 2, 0, 1, 1)
        self.input_detalle = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_detalle.setFont(font)
        self.input_detalle.setObjectName("input_detalle")
        self.gridLayout.addWidget(self.input_detalle, 5, 1, 1, 1)
        self.lbl_fecha_vencimiento = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_fecha_vencimiento.setFont(font)
        self.lbl_fecha_vencimiento.setObjectName("lbl_fecha_vencimiento")
        self.gridLayout.addWidget(self.lbl_fecha_vencimiento, 8, 0, 1, 1)
        self.lbl_cantidad = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_cantidad.setFont(font)
        self.lbl_cantidad.setObjectName("lbl_cantidad")
        self.gridLayout.addWidget(self.lbl_cantidad, 6, 0, 1, 1)
        self.lbl_codigo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_codigo.setFont(font)
        self.lbl_codigo.setObjectName("lbl_codigo")
        self.gridLayout.addWidget(self.lbl_codigo, 1, 0, 1, 1)
        self.input_cod = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_cod.setFont(font)
        self.input_cod.setObjectName("input_cod")
        self.gridLayout.addWidget(self.input_cod, 1, 1, 1, 1)
        self.lbl_detalle = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_detalle.setFont(font)
        self.lbl_detalle.setObjectName("lbl_detalle")
        self.gridLayout.addWidget(self.lbl_detalle, 5, 0, 1, 1)
        self.input_cantidad = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_cantidad.setFont(font)
        self.input_cantidad.setObjectName("input_cantidad")
        self.gridLayout.addWidget(self.input_cantidad, 6, 1, 1, 1)
        self.input_precio = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_precio.setFont(font)
        self.input_precio.setObjectName("input_precio")
        self.gridLayout.addWidget(self.input_precio, 9, 1, 1, 1)
        self.input_lote = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.input_lote.setFont(font)
        self.input_lote.setObjectName("input_lote")
        self.gridLayout.addWidget(self.input_lote, 2, 1, 1, 1)
        self.input_nombre = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_nombre.setFont(font)
        self.input_nombre.setObjectName("input_nombre")
        self.gridLayout.addWidget(self.input_nombre, 3, 1, 1, 1)
        self.lbl_agregarProducto = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_agregarProducto.setFont(font)
        self.lbl_agregarProducto.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_agregarProducto.setObjectName("lbl_agregarProducto")
        self.gridLayout.addWidget(self.lbl_agregarProducto, 0, 0, 1, 5)
        self.btn_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar.setGeometry(QtCore.QRect(170, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_agregar.setFont(font)
        self.btn_agregar.setObjectName("btn_agregar")
        self.btn_borrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_borrar.setGeometry(QtCore.QRect(370, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_borrar.setFont(font)
        self.btn_borrar.setObjectName("btn_borrar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_fecha_ingreso.setPlaceholderText(_translate("MainWindow", "fecha_ingreso"))
        self.lbl_fecha_ingreso.setText(_translate("MainWindow", "Fecha Ingreso:"))
        self.lbl_nombre.setText(_translate("MainWindow", "Nombre: "))
        self.lbl_precio.setText(_translate("MainWindow", "Precio: "))
        self.input_fecha_vencimiento.setPlaceholderText(_translate("MainWindow", "fecha_vencimiento"))
        self.lbl_lote.setText(_translate("MainWindow", "Lote:"))
        self.input_detalle.setPlaceholderText(_translate("MainWindow", "detalle"))
        self.lbl_fecha_vencimiento.setText(_translate("MainWindow", "Fecha Vencimiento: "))
        self.lbl_cantidad.setText(_translate("MainWindow", "Cantidad: "))
        self.lbl_codigo.setText(_translate("MainWindow", "Código: "))
        self.input_cod.setPlaceholderText(_translate("MainWindow", "código"))
        self.lbl_detalle.setText(_translate("MainWindow", "Detalle: "))
        self.input_cantidad.setPlaceholderText(_translate("MainWindow", "cantidad"))
        self.input_precio.setPlaceholderText(_translate("MainWindow", "precio"))
        self.input_lote.setPlaceholderText(_translate("MainWindow", "lote"))
        self.input_nombre.setPlaceholderText(_translate("MainWindow", "nombre"))
        self.lbl_agregarProducto.setText(_translate("MainWindow", "Agregar Producto "))
        self.btn_agregar.setText(_translate("MainWindow", "AGREGAR"))
        self.btn_borrar.setText(_translate("MainWindow", "BORRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
